### ISSUE TITLE
Request to add a function

### ISSUE THREAD

**Issue by Lok3rn3t** [rfresh2/ZenithProxy#105]
Add a command to terminate the program, the shutdown command constantly restarts the program

**Comment by Quadragintillion** [comment]
Ctrl+C

**Comment by Lok3rn3t** [comment]
I know, but since I'm writing my web panel to manage the server, I can only send commands

**Comment by rfresh2** [comment]
If you don't use the launcher and run the jar directly then it doesn't get restarted when you use the shutdown or restart commands

But also you will need to disable the autoupdater or things will get not work correctly 

Web panels and guis are not supported so you're on your own with how u get it to work and manage it
