### ISSUE TITLE
Disconnecting causes log spam (on some servers)

### ISSUE THREAD

**Issue by Quadragintillion** [rfresh2/ZenithProxy#106]
I tried using the proxy to connect to play.invadedlands.net and when I wasn't connected, it kept spamming the logs with "[Cache] [WARN] Invalid slot 45 for containerId 0"

**Comment by rfresh2** [comment]
I've moved those logs to the debug level and added some more checks https://github.com/rfresh2/ZenithProxy/commit/16acfa4e5920eba8aae92d191bf5e8db86060448

But I'm not going to support you using ZenithProxy on servers that don't allow it. And the server you linked clearly does not allow it.
