### ISSUE TITLE
Launcher not starting

### ISSUE THREAD

**Issue by musheck** [rfresh2/ZenithProxy#145]
Tried both python & windows launcher, windows exe file just disappears after opening, and python closes itself after setup.

Checked windows defender, doesn't block the exe file.

Python 3.1 is installed, tried both the launch.sh in terminal and launch.bat in folder, won't do anything past setup.

**Comment by rfresh2** [comment]
For the python launcher you need to run it from inside a terminal like `cmd`

You can't double click the `launch.bat` file and run it.

After you open `cmd` you will need to change directories to wherever you have the launcher files using `cd`:

For example: `cd "C:\Users\rfresh\ZenithProxy"`

Then run the script: `.\launch.bat`

If there are any errors it will show them.

For more support ask on my discord server so its easier to communicate quickly
