### ISSUE TITLE
Add support for cracked accounts

### ISSUE THREAD

**Issue by Veslydev** [rfresh2/ZenithProxy#149]
To farm in a private or a public cracked server with use of ZenithProxy

**Comment by ghost** [comment]
You basically Can't use other server than 2b2t, i'm trying to get it to work on Palanarchy rn, not sure it will work

**Comment by rfresh2** [comment]
You can play on any server currently using the `server` command

however, cracked accounts violate the Minecraft EULA and is illegal. ZenithProxy requires that you own the game.

**Comment by Veslydev** [comment]
you can add microsoft and then allow cracked users prism lsincher is like this

also why im asking this feature is i got banned from Xbox live 2.50 am idk why zenith proxy was connecting wnd reconnecting after and after i don't think its from that but it might be
