### ISSUE TITLE
Kicked after login

### ISSUE THREAD

**Issue by yusoxd** [rfresh2/ZenithProxy#152]
![image](https://github.com/user-attachments/assets/a7ee643c-4e99-4b79-a724-f1565a4bf18c)
getting disconnected after logging in
same thing also happened yesterday but it kicked me a few hours later after logging in

error: Error during client disconnect java.net.SocketException: Connection reset

edit: tested out on other servers, still getting kicked

**Comment by rfresh2** [comment]
https://github.com/rfresh2/ZenithProxy/wiki/Disconnects#connection-issue

**Comment by yusoxd** [comment]
> https://github.com/rfresh2/ZenithProxy/wiki/Disconnects#connection-issue

thank you
