### ISSUE TITLE
Change version

### ISSUE THREAD

**Issue by yusoxd** [rfresh2/ZenithProxy#161]
proxy logs into 2b2t as 1.21.1 and silent rotations doesnt work on that version. Viafabricplus doesnt work and i want the proxy to login to servers as 1.20.6 how do i do that?

**Comment by rfresh2** [comment]
answered on discord

`via zenithToServer` command

`autoConfig` off
`disableOn2b2t` off
`version` whatever mc version u want

https://github.com/rfresh2/ZenithProxy/wiki/Commands#via
