### ISSUE TITLE
add support for offline accounts to connect to the proxy

### ISSUE THREAD

**Issue by prljav** [rfresh2/ZenithProxy#164]
NOT A DUP OF #149 

allow for offline accounts to connect to zenith proxy, the account zenith proxy connects to the server is still a microsoft one, but the account that connects to zenith is a offline one, does not breach any eula or anything similar, just a qol feature

**Comment by rfresh2** [comment]
https://github.com/rfresh2/ZenithProxy/wiki/Commands#unsupported

specifically the `verifyUsers` setting
