### ISSUE TITLE
Docker setup

### ISSUE THREAD

**Issue by kdh8219** [rfresh2/ZenithProxy#48]
How about docker option?

**Comment by rfresh2** [comment]
![Discord_ecGm3S55bR](https://github.com/rfresh2/ZenithProxy/assets/89827146/cc1a38be-b993-4b59-94ec-55e80e48ae7d)

**Comment by broot5** [comment]
I wrote a [Dockerfile](https://gist.github.com/broot5/faf7d2a21ad2bd320b7bc669125650d6) for my own use.
