### ISSUE TITLE
Error when starting

### ISSUE THREAD

**Issue by LachCrafter** [rfresh2/ZenithProxy#51]
Launching ZenithProxy...
  File "update_launcher.py", line 49
    url = f"/repos/{repo_owner}/{repo_name}/releases/tags/{tag}"
                                                               ^
SyntaxError: invalid syntax
  File "launcher.py", line 181
    url = f"/repos/{repo_owner}/{repo_name}/releases?{urllib.parse.urlencode({'per_page': 100})}"
                                                                                                ^

**Comment by rfresh2** [comment]
update your python version
