### ISSUE TITLE
add the ability to disable the white list and the ability for cracked (non-premium) accounts to log into the proxy server

### ISSUE THREAD

**Issue by dav2010ID** [rfresh2/ZenithProxy#56]

**Comment by rfresh2** [comment]
you can already disable the whitelist in the `config.json`
![idea64_pS9XlnDfMM](https://github.com/rfresh2/ZenithProxy/assets/89827146/3dfb5f56-9869-45d2-b997-c5be98db1e33)

and then to allow non-verified accounts:
![idea64_nAMynjlJ5W](https://github.com/rfresh2/ZenithProxy/assets/89827146/401bca95-98fe-4d45-b4d8-297a14e91544)

In almost all cases i think disabling these two is a terrible idea. Anyone on the internet could connect to your proxy. 

I will not create commands to configure these easily. If you want to shoot yourself in the foot, you have to jump through some extra manual editing hoops.
