### ISSUE TITLE
Teams don't work correctly

### ISSUE THREAD

**Issue by xpdlx** [rfresh2/ZenithProxy#70]
Hey, I've been using ZenithProxy for a couple of days and I love it!

I noticed that teams don't always work correctly, names sometimes show up as white. I think it could be using an internal ZenithProxy team? This isn't a big issue by itself, but my main concern is that this also makes it so you get collision from other players. 

On my own server teams don't seem to work at all. Players names are always white. (my server just uses vanilla teams).

On another server I tried, teams do work at first, but if you relog (while keeping the account online). people's names will be white in tab. (I don't think the teams on this server actually "exist", the colors in tab are just for ranks)

**Comment by rfresh2** [comment]
teams aren't cached at the proxy because 2b2t doesn't have teams

i'm not against someone adding it but its not high up on my own priorities right now
