### ISSUE TITLE
how do i connect to it on minecraft?

### ISSUE THREAD

**Issue by ScHc4043** [rfresh2/ZenithProxy#78]
it just says already connected then on the console like warn USER joined uuid then ip and stuff

**Comment by rfresh2** [comment]
If you're hosting zenith on your home PC there will be LAN server listing that appears in your MC client.

If you host it on a VPS like DigitalOcean you can connect to it using the public IP address of the VPS and port you configured at setup, `<ip>:<port>`

also you will need to whitelist the account you're connecting with using the `whitelist add <player>` command
