### ISSUE TITLE
Command overlap with vanilla

### ISSUE THREAD

**Issue by Doogie13** [rfresh2/ZenithProxy#96]
If I were to use this proxy to connect to a server other than 2b2t on which I have admin, using commands such as /whitelist are overridden by ZenithProxy, meaning I can't use them. 

This is a minor nit-pick but its probably worth fixing.

**Comment by rfresh2** [comment]
You can disable zenith's in-game slash commands already. 

See `help commandConfig`

In-game commands alternatively use the `!` prefix which can't conflict with server commands. You just don't get the nice command completion like with slash commands

**Comment by Doogie13** [comment]
Thanks
