### ISSUE TITLE
ping doesn't display correctly

### ISSUE THREAD

**Issue by Xenapte** [rfresh2/ZenithProxy#98]
The proxy is deployed on a server that has quite some network latency to me, but for some reason it always displays 0ms ingame. Since the original server tab shows the ping from my proxy, there's no way for me to know my actual ping.

TCP Ping to my proxy server:
![T2{(WU2NM2Z6({KK2C~O9_N](https://github.com/rfresh2/ZenithProxy/assets/17661805/b9578286-23cc-4989-8ad8-83d12f845898)

Ingame tab:
![](https://github.com/rfresh2/ZenithProxy/assets/17661805/ff921773-55c7-44ce-ba30-ba894413c90a)

**Comment by rfresh2** [comment]
resolved by https://github.com/rfresh2/ZenithProxy/commit/07220ccf6971b147f1e96701cef12acf4e546f81

**Comment by rfresh2** [comment]
note that some servers will not report ping at all in their tablist, so this is not a universal fix

**Comment by Xenapte** [comment]
Sorry to bother you again, but is there a way to know my ping to the proxy itself (like on the server list screen)? It now shows the ping from proxy to the actual server though, so thanks at least for the partial fix.
![WID{PVI 9)63JS_IFOANILF](https://github.com/rfresh2/ZenithProxy/assets/17661805/06693f2e-6c49-421d-b6d6-affda5a118e6)

**Comment by rfresh2** [comment]
the server list screen's ping number is calculated on your client based on how long it took to receive the response. so no, there's not a simple way to make that show the same as the destination MC server.

your ping as a player to zenith is that left-most number on the tablist. and the ping from zenith to the destination server is on the right. your total ping is the sum of those two.

**Comment by Xenapte** [comment]
> the server list screen's ping number is calculated on your client based on how long it took to receive the response. so no, there's not a simple way to make that show the same as the destination MC server.
> 
> your ping as a player to zenith is that left-most number on the tablist. and the ping from zenith to the destination server is on the right. your total ping is the sum of those two.

Yeah I figured this out. But as said above, my proxy is on a server that I have quite some ping with, but it still shows up as 0ms. So I'd like to know if it's possible to fix this so I can sum these 2 up and get my actual ping.

**Comment by rfresh2** [comment]
ok i see what you mean now

should be resolved by https://github.com/rfresh2/ZenithProxy/commit/f0baa8316b6ed380779e2e033f484f73f8c4fd25

servers that don't use the same anticheat as 2b2t, grim , (or none at all) don't send regular ping packets. so i made it also use keepalives to update your ping, which zenith always sends like a normal mc server

**Comment by Xenapte** [comment]
Alright this works pretty well, thanks!
